# 应用名称
server:
  port: 18080

spring:
  profiles:
    active: dev
  application:
    name: liuyun-gateway
  redis:
    host: 123.57.73.216
    port: 6379
    database: 0
    password:
    timeout: 10000
    lettuce:
      pool:
        min-idle: 0
        max-wait: -1
        max-active: 8
        max-idle: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.73.216:3306/liu_yun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root@0928
  cloud:
    nacos:
      discovery:
        group: liuyun
        server-addr: 123.57.73.216:8848
        namespace: 30dd5d56-8bec-48eb-94dc-5851cc2e16cd
        service: ${spring.application.name}
        weight: 1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: liuyun-user
          uri: lb://liuyun-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/liuyun-user
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true

mybatis-plus:
  typeEnumsPackage: com.liuyun.core.mybatisplus.enums
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.liuyun.model.*.entity.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    auto-mapping-behavior: full
  global-config:
    banner: false
    db-config:
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS